// flow-typed signature: 28f1b357cb0b34f06dcd83a11f503ec6
// flow-typed version: <<STUB>>/@appearhere/react-input-range_v^1.2.0/flow_v0.117.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@appearhere/react-input-range'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@appearhere/react-input-range' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@appearhere/react-input-range/dist/@appearhere/react-input-range' {
  declare module.exports: any;
}

declare module '@appearhere/react-input-range/dist/@appearhere/react-input-range.min' {
  declare module.exports: any;
}

declare module '@appearhere/react-input-range/lib/InputRange/defaultClassNames' {
  declare module.exports: any;
}

declare module '@appearhere/react-input-range/lib/InputRange' {
  declare module.exports: any;
}

declare module '@appearhere/react-input-range/lib/InputRange/InputRange' {
  declare module.exports: any;
}

declare module '@appearhere/react-input-range/lib/InputRange/Label' {
  declare module.exports: any;
}

declare module '@appearhere/react-input-range/lib/InputRange/propTypes' {
  declare module.exports: any;
}

declare module '@appearhere/react-input-range/lib/InputRange/Slider' {
  declare module.exports: any;
}

declare module '@appearhere/react-input-range/lib/InputRange/Track' {
  declare module.exports: any;
}

declare module '@appearhere/react-input-range/lib/InputRange/util' {
  declare module.exports: any;
}

declare module '@appearhere/react-input-range/lib/InputRange/valueTransformer' {
  declare module.exports: any;
}

// Filename aliases
declare module '@appearhere/react-input-range/dist/@appearhere/react-input-range.js' {
  declare module.exports: $Exports<'@appearhere/react-input-range/dist/@appearhere/react-input-range'>;
}
declare module '@appearhere/react-input-range/dist/@appearhere/react-input-range.min.js' {
  declare module.exports: $Exports<'@appearhere/react-input-range/dist/@appearhere/react-input-range.min'>;
}
declare module '@appearhere/react-input-range/lib/InputRange/defaultClassNames.js' {
  declare module.exports: $Exports<'@appearhere/react-input-range/lib/InputRange/defaultClassNames'>;
}
declare module '@appearhere/react-input-range/lib/InputRange/index' {
  declare module.exports: $Exports<'@appearhere/react-input-range/lib/InputRange'>;
}
declare module '@appearhere/react-input-range/lib/InputRange/index.js' {
  declare module.exports: $Exports<'@appearhere/react-input-range/lib/InputRange'>;
}
declare module '@appearhere/react-input-range/lib/InputRange/InputRange.js' {
  declare module.exports: $Exports<'@appearhere/react-input-range/lib/InputRange/InputRange'>;
}
declare module '@appearhere/react-input-range/lib/InputRange/Label.js' {
  declare module.exports: $Exports<'@appearhere/react-input-range/lib/InputRange/Label'>;
}
declare module '@appearhere/react-input-range/lib/InputRange/propTypes.js' {
  declare module.exports: $Exports<'@appearhere/react-input-range/lib/InputRange/propTypes'>;
}
declare module '@appearhere/react-input-range/lib/InputRange/Slider.js' {
  declare module.exports: $Exports<'@appearhere/react-input-range/lib/InputRange/Slider'>;
}
declare module '@appearhere/react-input-range/lib/InputRange/Track.js' {
  declare module.exports: $Exports<'@appearhere/react-input-range/lib/InputRange/Track'>;
}
declare module '@appearhere/react-input-range/lib/InputRange/util.js' {
  declare module.exports: $Exports<'@appearhere/react-input-range/lib/InputRange/util'>;
}
declare module '@appearhere/react-input-range/lib/InputRange/valueTransformer.js' {
  declare module.exports: $Exports<'@appearhere/react-input-range/lib/InputRange/valueTransformer'>;
}
