// flow-typed signature: 3fbb50f53c491ef8e3e1d8d4fc312960
// flow-typed version: <<STUB>>/@appearhere/react-stickynode_v^1.0.1/flow_v0.117.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@appearhere/react-stickynode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@appearhere/react-stickynode' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@appearhere/react-stickynode/dist/Sticky' {
  declare module.exports: any;
}

declare module '@appearhere/react-stickynode/Gruntfile' {
  declare module.exports: any;
}

// Filename aliases
declare module '@appearhere/react-stickynode/dist/Sticky.js' {
  declare module.exports: $Exports<'@appearhere/react-stickynode/dist/Sticky'>;
}
declare module '@appearhere/react-stickynode/Gruntfile.js' {
  declare module.exports: $Exports<'@appearhere/react-stickynode/Gruntfile'>;
}
declare module '@appearhere/react-stickynode/index' {
  declare module.exports: $Exports<'@appearhere/react-stickynode'>;
}
declare module '@appearhere/react-stickynode/index.js' {
  declare module.exports: $Exports<'@appearhere/react-stickynode'>;
}
