module.exports = { vars:
   { '--color-white': 'rgb(255, 255, 255)',
     '--color-black': 'rgb(25, 25, 25)',
     '--color-gold': 'rgb(0, 0, 0)',
     '--color-gold--light': 'rgb(219, 189, 154)',
     '--color-blue': 'rgb(25, 103, 158)',
     '--color-red': 'rgb(213, 84, 68)',
     '--color-green': 'rgb(72, 213, 108)',
     '--color-orange': 'rgb(234, 155, 82)',
     '--color-yellow': 'rgb(236, 180, 74)',
     '--color-focusRing': 'rgb(91, 157, 217)',
     '--color-red--light': 'rgb(236, 94, 77)',
     '--color-blue--light': 'rgb(41, 125, 184)',
     '--color-greyLightest': 'rgb(245, 245, 245)',
     '--color-greyLighter': 'rgb(221, 221, 221)',
     '--color-greyLight': 'rgb(190, 190, 190)',
     '--color-grey': 'rgb(139, 139, 139)',
     '--color-greyDark': 'rgb(90, 90, 90)',
     '--color-greyDarker': 'rgb(56, 56, 56)',
     '--color-greyDarkest': 'rgb(35, 35, 35)',
     '--color-transparent-black-i': 'rgba(25, 25, 25, 0.8)',
     '--color-transparent-black-ii': 'rgba(25, 25, 25, 0.6)',
     '--color-transparent-black-iii': 'rgba(25, 25, 25, 0.4)',
     '--color-transparent-black-iv': 'rgba(25, 25, 25, 0.2)',
     '--overlay-default': 'rgba(20, 20, 21, 0.5)',
     '--color-primary': 'var(--color-gold)',
     '--color-action': 'var(--color-blue)',
     '--color-success': 'var(--color-green)',
     '--color-danger': 'var(--color-red)',
     '--color-primary--light': 'var(--color-gold--light)',
     '--color-danger--light': 'var(--color-red--light)',
     '--color-action--light': 'var(--color-blue--light)',
     '--color-available': 'var(--color-green)',
     '--color-unavailable': 'var(--color-red)',
     '--color-underOffer': 'var(--color-orange)',
     '--color-internal': 'var(--color-black)',
     '--color-void': 'var(--color-yellow)',
     '--facebook-blue': 'rgb(59, 89, 152)',
     '--twitter-blue': 'rgb(29, 161, 242)',
     '--pintrest-red': 'rgb(190, 9, 28)',
     '--ios-safari-bottom-margin': '44px',
     '--destination-listing-content-height': '7.375rem',
     '--destination-listing-image-height': '8.4375rem',
     '--z-1': '10',
     '--z-2': '20',
     '--z-3': '30',
     '--z-4': '40',
     '--z-5': '50',
     '--z-6': '60',
     '--z-7': '70',
     '--z-8': '80',
     '--z-9': '90',
     '--z-modal': 'var(--z-8)',
     '--z-floatingActionBtn': 'var(--z-6)',
     '--z-stickyNode': 'var(--z-5)',
     '--z-tooltip': 'var(--z-3)',
     '--z-mapCanvas': 'var(--z-1)',
     '--z-mapMarker': 'var(--z-2)',
     '--z-mapControls': 'var(--z-3)',
     '--z-offcanvasPanel': 'var(--z-7)',
     '--z-overlay': 'var(--z-7)',
     '--font-avenir': '\'Avenir Next W01\', \'Helvetica Neue\', \'Helvetica\', \'sans-serif\'',
     '--font-fira-code': '\'Fira Mono\', monospace',
     '--fontweight-bold': '800',
     '--fontweight-demi': '700',
     '--fontweight-regular': '400',
     '--fontsize-large-v': '2.75rem',
     '--fontsize-large-iv': '2rem',
     '--fontsize-large-iii': '1.75rem',
     '--fontsize-large-ii': '1.5rem',
     '--fontsize-large-i': '1.1875rem',
     '--fontsize-regular': '1rem',
     '--fontsize-small-i': '0.875rem',
     '--fontsize-small-ii': '0.6875rem',
     '--font-large-v': 'var(--fontweight-bold) var(--fontsize-large-v)/var(--lineheight-large-v) var(--font-avenir)',
     '--font-large-iv': 'var(--fontweight-demi) var(--fontsize-large-iv)/var(--lineheight-large-iv) var(--font-avenir)',
     '--font-large-iii': 'var(--fontweight-demi) var(--fontsize-large-iii)/var(--lineheight-large-iii) var(--font-avenir)',
     '--font-large-ii': 'var(--fontweight-demi) var(--fontsize-large-ii)/var(--lineheight-large-ii) var(--font-avenir)',
     '--font-large-i': 'var(--fontweight-regular) var(--fontsize-large-i)/var(--lineheight-large-i) var(--font-avenir)',
     '--font-regular': 'var(--fontweight-regular) var(--fontsize-regular)/var(--lineheight-regular) var(--font-avenir)',
     '--font-small-i': 'var(--fontweight-regular) var(--fontsize-small-i)/var(--lineheight-small-i) var(--font-avenir)',
     '--font-small-ii': 'var(--fontweight-regular) var(--fontsize-small-ii)/var(--lineheight-small-ii) var(--font-avenir)',
     '--lineheight-large-v': '0.8148',
     '--lineheight-large-iv': '1.34375',
     '--lineheight-large-iii': '1.28571',
     '--lineheight-large-ii': '1.333',
     '--lineheight-large-i': '1.263',
     '--lineheight-regular': '1.4375',
     '--lineheight-small-i': '1.285',
     '--lineheight-small-ii': '1.363',
     '--letter-spacing-large-v': '0.32rem',
     '--letter-spacing-large-iv': '0.01875rem',
     '--letter-spacing-large-iii': '0.01875rem',
     '--letter-spacing-large-ii': '0.01875rem',
     '--letter-spacing-large-i': '0.0125rem',
     '--letter-spacing-regular': '0.010625rem',
     '--letter-spacing-small-i': '0.009375rem',
     '--letter-spacing-small-ii': '0.009375rem',
     '--letterspacing-wide': '0.125rem',
     '--letterspacing-less-wide': '0.009375rem',
     '--size-lg-vii': '12.5rem',
     '--size-lg-vi': '9rem',
     '--size-lg-v': '6rem',
     '--size-lg-iv': '5rem',
     '--size-lg-iii': '4rem',
     '--size-lg-ii': '3rem',
     '--size-lg-i': '1.5rem',
     '--size-regular': '1rem',
     '--size-sm-i': '0.75rem',
     '--size-sm-ii': '0.5rem',
     '--size-sm-iii': '0.25rem',
     '--size-sm-iv': '0.1rem',
     '--space-200': 'var(--size-lg-vii)',
     '--space-144': 'var(--size-lg-vi)',
     '--space-96': 'var(--size-lg-v)',
     '--space-80': 'var(--size-lg-iv)',
     '--space-64': 'var(--size-lg-iii)',
     '--space-48': 'var(--size-lg-ii)',
     '--size-large': 'var(--size-lg-i)',
     '--size-medium': 'var(--size-regular)',
     '--size-small': 'var(--size-sm-ii)',
     '--size-micro': 'var(--size-sm-iii)',
     '--animation-sharp': 'cubic-bezier(0,1,0.75,1)' },
  media:
   { '--hero-width-lg-i': '(min-width: 50rem)',
     '--hero-height-lg-i': '(min-height: 50rem)',
     '--hero-height-lg-ii': '(min-height: 64rem)',
     '--wrapper-large': '(min-width: 62.25rem)',
     '--signpost-full': '(min-width: 31.25rem)',
     '--squareHero-lg-i': '(min-width: 25rem)',
     '--squareHero-lg-ii': '(min-width: 46.875rem)',
     '--squareHero-lg-iii': '(min-width: 62.5rem)',
     '--modal-lg': '(min-width: 37.5rem)',
     '--scaffold-dl-lg-i': '(min-width: 30rem)',
     '--colors-2up': '(min-width: 25rem)',
     '--colors-3up': '(min-width: 50rem)',
     '--iconography-3up': '(min-width: 31.875rem)',
     '--iconography-4up': '(min-width: 50rem)',
     '--typography-2up': '(min-width: 25rem)',
     '--typography-3up': '(min-width: 50rem)',
     '--medallion-2up': '(min-width: 31.875rem)',
     '--controls-transpose': '(min-width: 35rem)' },
  selector: {} };