# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

workflows:
  unit-test:
    jobs:
      - node/test:
          pkg-manager: yarn 
          version: '12.22' 
