// flow-typed signature: 5b0e840bce9c0b6156f8c0caab904db4
// flow-typed version: <<STUB>>/object-fit-images_v^3.2.3/flow_v0.117.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'object-fit-images'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'object-fit-images' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'object-fit-images/dist/ofi.common-js' {
  declare module.exports: any;
}

declare module 'object-fit-images/dist/ofi.es-modules' {
  declare module.exports: any;
}

declare module 'object-fit-images/dist/ofi' {
  declare module.exports: any;
}

declare module 'object-fit-images/dist/ofi.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'object-fit-images/dist/ofi.common-js.js' {
  declare module.exports: $Exports<'object-fit-images/dist/ofi.common-js'>;
}
declare module 'object-fit-images/dist/ofi.es-modules.js' {
  declare module.exports: $Exports<'object-fit-images/dist/ofi.es-modules'>;
}
declare module 'object-fit-images/dist/ofi.js' {
  declare module.exports: $Exports<'object-fit-images/dist/ofi'>;
}
declare module 'object-fit-images/dist/ofi.min.js' {
  declare module.exports: $Exports<'object-fit-images/dist/ofi.min'>;
}
