// flow-typed signature: a9d266bab445035cfb8447991e062664
// flow-typed version: <<STUB>>/react-moment-proptypes_v^1.5.0/flow_v0.117.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-moment-proptypes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-moment-proptypes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-moment-proptypes/src/core' {
  declare module.exports: any;
}

declare module 'react-moment-proptypes/src' {
  declare module.exports: any;
}

declare module 'react-moment-proptypes/src/messages' {
  declare module.exports: any;
}

declare module 'react-moment-proptypes/src/moment-validation-wrapper' {
  declare module.exports: any;
}

declare module 'react-moment-proptypes/test/core' {
  declare module.exports: any;
}

declare module 'react-moment-proptypes/test/integration/duration-obj-tests' {
  declare module.exports: any;
}

declare module 'react-moment-proptypes/test/integration/moment-obj-tests' {
  declare module.exports: any;
}

declare module 'react-moment-proptypes/test/integration/moment-string-tests' {
  declare module.exports: any;
}

declare module 'react-moment-proptypes/test/integration/predicate-tests' {
  declare module.exports: any;
}

declare module 'react-moment-proptypes/test/integration/util' {
  declare module.exports: any;
}

declare module 'react-moment-proptypes/test/moment-validation-wrapper-tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-moment-proptypes/src/core.js' {
  declare module.exports: $Exports<'react-moment-proptypes/src/core'>;
}
declare module 'react-moment-proptypes/src/index' {
  declare module.exports: $Exports<'react-moment-proptypes/src'>;
}
declare module 'react-moment-proptypes/src/index.js' {
  declare module.exports: $Exports<'react-moment-proptypes/src'>;
}
declare module 'react-moment-proptypes/src/messages.js' {
  declare module.exports: $Exports<'react-moment-proptypes/src/messages'>;
}
declare module 'react-moment-proptypes/src/moment-validation-wrapper.js' {
  declare module.exports: $Exports<'react-moment-proptypes/src/moment-validation-wrapper'>;
}
declare module 'react-moment-proptypes/test/core.js' {
  declare module.exports: $Exports<'react-moment-proptypes/test/core'>;
}
declare module 'react-moment-proptypes/test/integration/duration-obj-tests.js' {
  declare module.exports: $Exports<'react-moment-proptypes/test/integration/duration-obj-tests'>;
}
declare module 'react-moment-proptypes/test/integration/moment-obj-tests.js' {
  declare module.exports: $Exports<'react-moment-proptypes/test/integration/moment-obj-tests'>;
}
declare module 'react-moment-proptypes/test/integration/moment-string-tests.js' {
  declare module.exports: $Exports<'react-moment-proptypes/test/integration/moment-string-tests'>;
}
declare module 'react-moment-proptypes/test/integration/predicate-tests.js' {
  declare module.exports: $Exports<'react-moment-proptypes/test/integration/predicate-tests'>;
}
declare module 'react-moment-proptypes/test/integration/util.js' {
  declare module.exports: $Exports<'react-moment-proptypes/test/integration/util'>;
}
declare module 'react-moment-proptypes/test/moment-validation-wrapper-tests.js' {
  declare module.exports: $Exports<'react-moment-proptypes/test/moment-validation-wrapper-tests'>;
}
