// flow-typed signature: 9043933a9c277b08c8e3603576e8770b
// flow-typed version: <<STUB>>/react-on-visible_v^1.5.0/flow_v0.117.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-on-visible'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-on-visible' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-on-visible/build/bundle' {
  declare module.exports: any;
}

declare module 'react-on-visible/build' {
  declare module.exports: any;
}

declare module 'react-on-visible/build/lib/bindRaf' {
  declare module.exports: any;
}

declare module 'react-on-visible/build/lib/debounce' {
  declare module.exports: any;
}

declare module 'react-on-visible/src' {
  declare module.exports: any;
}

declare module 'react-on-visible/src/lib/bindRaf' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-on-visible/build/bundle.js' {
  declare module.exports: $Exports<'react-on-visible/build/bundle'>;
}
declare module 'react-on-visible/build/index' {
  declare module.exports: $Exports<'react-on-visible/build'>;
}
declare module 'react-on-visible/build/index.js' {
  declare module.exports: $Exports<'react-on-visible/build'>;
}
declare module 'react-on-visible/build/lib/bindRaf.js' {
  declare module.exports: $Exports<'react-on-visible/build/lib/bindRaf'>;
}
declare module 'react-on-visible/build/lib/debounce.js' {
  declare module.exports: $Exports<'react-on-visible/build/lib/debounce'>;
}
declare module 'react-on-visible/src/index' {
  declare module.exports: $Exports<'react-on-visible/src'>;
}
declare module 'react-on-visible/src/index.js' {
  declare module.exports: $Exports<'react-on-visible/src'>;
}
declare module 'react-on-visible/src/lib/bindRaf.js' {
  declare module.exports: $Exports<'react-on-visible/src/lib/bindRaf'>;
}
