// flow-typed signature: f21398442d65ecba6c60d4772987d51a
// flow-typed version: <<STUB>>/react-container-query_v^0.11.0/flow_v0.117.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-container-query'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-container-query' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-container-query/dist/react-container-query' {
  declare module.exports: any;
}

declare module 'react-container-query/dist/react-container-query.min' {
  declare module.exports: any;
}

declare module 'react-container-query/lib/ContainerQueryCore' {
  declare module.exports: any;
}

declare module 'react-container-query/lib' {
  declare module.exports: any;
}

declare module 'react-container-query/lib/interfaces' {
  declare module.exports: any;
}

declare module 'react-container-query/lib/isShallowEqual' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-container-query/dist/react-container-query.js' {
  declare module.exports: $Exports<'react-container-query/dist/react-container-query'>;
}
declare module 'react-container-query/dist/react-container-query.min.js' {
  declare module.exports: $Exports<'react-container-query/dist/react-container-query.min'>;
}
declare module 'react-container-query/lib/ContainerQueryCore.js' {
  declare module.exports: $Exports<'react-container-query/lib/ContainerQueryCore'>;
}
declare module 'react-container-query/lib/index' {
  declare module.exports: $Exports<'react-container-query/lib'>;
}
declare module 'react-container-query/lib/index.js' {
  declare module.exports: $Exports<'react-container-query/lib'>;
}
declare module 'react-container-query/lib/interfaces.js' {
  declare module.exports: $Exports<'react-container-query/lib/interfaces'>;
}
declare module 'react-container-query/lib/isShallowEqual.js' {
  declare module.exports: $Exports<'react-container-query/lib/isShallowEqual'>;
}
