// flow-typed signature: 8c0b4b90a7361f5cf6ed3f401b59694e
// flow-typed version: <<STUB>>/react-html5video_v^2.5.1/flow_v0.117.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-html5video'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-html5video' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-html5video/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-html5video/dist/index' {
  declare module.exports: $Exports<'react-html5video/dist'>;
}
declare module 'react-html5video/dist/index.js' {
  declare module.exports: $Exports<'react-html5video/dist'>;
}
