// flow-typed signature: 9b132394085133ee83350ac657eab8b5
// flow-typed version: <<STUB>>/subscribe-ui-event_v^1.1.1/flow_v0.117.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'subscribe-ui-event'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'subscribe-ui-event' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'subscribe-ui-event/dist/AugmentedEvent' {
  declare module.exports: any;
}

declare module 'subscribe-ui-event/dist/constants' {
  declare module.exports: any;
}

declare module 'subscribe-ui-event/dist/globalVars' {
  declare module.exports: any;
}

declare module 'subscribe-ui-event/dist/lib/leIE8' {
  declare module.exports: any;
}

declare module 'subscribe-ui-event/dist/lib/listen' {
  declare module.exports: any;
}

declare module 'subscribe-ui-event/dist/lib/rAFThrottle' {
  declare module.exports: any;
}

declare module 'subscribe-ui-event/dist/lib/supportPassiveEvent' {
  declare module.exports: any;
}

declare module 'subscribe-ui-event/dist/mainEventConnectors' {
  declare module.exports: any;
}

declare module 'subscribe-ui-event/dist/subscribe' {
  declare module.exports: any;
}

declare module 'subscribe-ui-event/dist/unsubscribe' {
  declare module.exports: any;
}

declare module 'subscribe-ui-event/Gruntfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'subscribe-ui-event/dist/AugmentedEvent.js' {
  declare module.exports: $Exports<'subscribe-ui-event/dist/AugmentedEvent'>;
}
declare module 'subscribe-ui-event/dist/constants.js' {
  declare module.exports: $Exports<'subscribe-ui-event/dist/constants'>;
}
declare module 'subscribe-ui-event/dist/globalVars.js' {
  declare module.exports: $Exports<'subscribe-ui-event/dist/globalVars'>;
}
declare module 'subscribe-ui-event/dist/lib/leIE8.js' {
  declare module.exports: $Exports<'subscribe-ui-event/dist/lib/leIE8'>;
}
declare module 'subscribe-ui-event/dist/lib/listen.js' {
  declare module.exports: $Exports<'subscribe-ui-event/dist/lib/listen'>;
}
declare module 'subscribe-ui-event/dist/lib/rAFThrottle.js' {
  declare module.exports: $Exports<'subscribe-ui-event/dist/lib/rAFThrottle'>;
}
declare module 'subscribe-ui-event/dist/lib/supportPassiveEvent.js' {
  declare module.exports: $Exports<'subscribe-ui-event/dist/lib/supportPassiveEvent'>;
}
declare module 'subscribe-ui-event/dist/mainEventConnectors.js' {
  declare module.exports: $Exports<'subscribe-ui-event/dist/mainEventConnectors'>;
}
declare module 'subscribe-ui-event/dist/subscribe.js' {
  declare module.exports: $Exports<'subscribe-ui-event/dist/subscribe'>;
}
declare module 'subscribe-ui-event/dist/unsubscribe.js' {
  declare module.exports: $Exports<'subscribe-ui-event/dist/unsubscribe'>;
}
declare module 'subscribe-ui-event/Gruntfile.js' {
  declare module.exports: $Exports<'subscribe-ui-event/Gruntfile'>;
}
declare module 'subscribe-ui-event/index' {
  declare module.exports: $Exports<'subscribe-ui-event'>;
}
declare module 'subscribe-ui-event/index.js' {
  declare module.exports: $Exports<'subscribe-ui-event'>;
}
