import svgClean from '../../utils/svg-clean';

export default {
  'appearhere-brackets': svgClean(require('./icons/icon-appearhere-brackets.svg')),
  'chart-arrow': svgClean(require('./icons/icon-chart-arrow.svg')),
  'play-c': svgClean(require('./icons/icon-play-c.svg')),
  'tick-starred': svgClean(require('./icons/icon-tick-starred.svg')),
  'travel-idea': svgClean(require('./icons/icon-travel-idea.svg')),
  'vip-entrance': svgClean(require('./icons/icon-vip-entrance.svg')),
  appearhere: svgClean(require('./icons/icon-appearhere.svg')),
  bogroll: svgClean(require('./icons/icon-bogroll.svg')),
  camera: svgClean(require('./icons/icon-camera.svg')),
  chatting: svgClean(require('./icons/icon-chatting.svg')),
  comment: svgClean(require('./icons/icon-comment.svg')),
  dollar: svgClean(require('./icons/icon-dollar.svg')),
  download: svgClean(require('./icons/icon-download.svg')),
  globe: svgClean(require('./icons/icon-globe.svg')),
  manage: svgClean(require('./icons/icon-manage.svg')),
  percentage: svgClean(require('./icons/icon-percentage.svg')),
  play: svgClean(require('./icons/icon-play.svg')),
  search: svgClean(require('./icons/icon-search.svg')),
  shield: svgClean(require('./icons/icon-shield.svg')),
  signature: svgClean(require('./icons/icon-signature.svg')),
  tick: svgClean(require('./icons/icon-tick.svg')),
  ticket: svgClean(require('./icons/icon-ticket.svg')),
  teamwork: svgClean(require('./icons/icon-teamwork.svg')),
};