name: Lint

on: [pull_request]

jobs:
  flow:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.14.1

    - name: Install Dependancies
      run: |
        cd packages/core
        yarn install
    - name: Lint Flow
      run: |
        cd packages/core
        yarn run flow
